### ISSUE TITLE
Советы по оформлению кода

### ISSUE THREAD

**Issue by lyudchik** [Vlad-Bondar/Calculator#1]
# Советы по оформлению кода

##### 1.1.1 Неиспользование импортирований 
- "import java.math.MathContext"(AdditiomalOperation.java; строка 5);
- "import android.content.Context"(Start_activity.java; строка 3);

##### 1.1.2 Вопросы, связанные с проблемами кода
- "signNumber == true" следует заменить на "signNumber" (StartActivity.java; строка 392)
- "changeFlag == true" следует заменить на "changeFlag" (StartActivity.java; строка 317)
##### 1.1.4 Вероятные ошибки
- класс Convert нигде не используется 

##### 1.2.1 Дизайн и интернационализация
- Жестко привязанный к программе текст (activity_start.xml)
- Симметричность отступов (при задании paddingLeft следует задавать paddingRight для симметрии)

##### 1.2.2 Производительность
- Отрисовка областей более одного раза в файлах разметки (использование androidBackground и @app/Theme с таким же androidBackground)
- неиспользуемые элементы в файлах русурсов

##### 1.2.3 Юзабилити
- В файлах разметки используется атрибут "showAsActions=always". Предпочтительнее испоьзовать "showAsActions=ifRoom"
- В некоторых файлах разметки пропущен атрибут "inputType"

### 2. Правильность написания 
- некорректные названия элементов

**Comment by Vlad-Bondar** [comment]
Замечания принятны, изменения внесены.
